[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.31"
clap_autocomplete = "0.4.2"
human-panic = "2.0.2"
serde_json = "1.0.140"
serde = "1.0.219"
log = "0.4.27"
phf = { version = "0.11", features = ["macros"] }
convert_case = "0.8.0"
regress = "0.10.3"
